apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: attendance-autoscaler
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attendance
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
