apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: management-autoscaler
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: management
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
