apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reporting-autoscaler
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reporting
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60
