apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facenet-data-vol-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "io1"
  selector:
    matchExpressions:
      - {key: kubernetes.io/hostname, operator: In, values: [ip-192-168-33-3.us-east-2.compute.internal]}