apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-reporting-data-vol-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
