apiVersion: v1
kind: Service
metadata:
  name: attendance
  namespace: production
spec:
  selector:
    app: attendance
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: attendance
