apiVersion: v1
kind: Service
metadata:
  name: management
  namespace: production
spec:
  selector:
    app: management
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8083
      name: management
