apiVersion: v1
kind: Service
metadata:
  name: reporting
  namespace: production
spec:
  selector:
    app: reporting
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8084
    name: reporting
