apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: production
spec:
  selector:
    app: vault
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8200
    name: vault-ui
  - protocol: TCP
    port: 8200
    targetPort: 8200
    name: vault
