apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apm-server
  namespace: production
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:7.6.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8200