apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: production
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 30
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 30
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-data-vol
      securityContext:
         runAsUser: 1000
         fsGroup: 1000
      volumes:
      - name: elastic-data-vol
        persistentVolumeClaim:
          claimName: elastic-data-vol-claim