apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: production
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "example"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data-vol
      volumes:
      - name: mongo-data-vol
        persistentVolumeClaim:
          claimName: mongo-data-vol-claim
          readOnly: false