apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - image: bitnami/spark:2
          name: spark-worker
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: SPARK_MASTER_URL
              value: "spark://spark:7077"
            - name: SPARK_WORKER_MEMORY
              value: "1G"
            - name: SPARK_WORKER_CORES
              value: "1"
          imagePullPolicy: Always
          ports:
            - name: worker-ui
              containerPort: 8081
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
status: {}
