apiVersion: v1
kind: Service
metadata:
  name: adminui
  namespace: production
spec:
  selector:
    app: adminui
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: adminui