apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: production
spec:
  selector:
    app: apm-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
    name: apm-server