apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: production
spec:
  selector:
    app: broker
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 29092
    targetPort: 29092
    name: broker