apiVersion: v1
kind: Service
metadata:
  name: control-center
  namespace: production
spec:
  selector:
    app: control-center
#  type: LoadBalancer
  type: ClusterIP
  ports:
  - protocol: TCP
#   port: 80
    port: 9021
    targetPort: 9021
    name: control-center