apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: production
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    name: elasticsearch