apiVersion: v1
kind: Service
metadata:
  name: facenet
  namespace: production
spec:
  selector:
    app: facenet
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: facenet