apiVersion: v1
kind: Service
metadata:
  name: hexagon
  namespace: production
spec:
  selector:
    app: hexagon
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: attendance
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: user
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: management
    - protocol: TCP
      port: 8084
      targetPort: 8084
      name: reporting
