apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: production
spec:
  selector:
    app: kibana
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    name: kibana