apiVersion: v1
kind: Service
metadata:
  name: mongo-management
  namespace: production
spec:
  selector:
    app: mongo-management
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongo-management
