apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: production
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo