apiVersion: v1
kind: Service
metadata:
  name: srs
  namespace: production
spec:
  selector:
    app: srs
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1935
    targetPort: 1935
    name: rtmp
  - protocol: TCP
    port: 1985
    targetPort: 1985
    name: rtmp-conn
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: rtmp-ui