apiVersion: v1
kind: Service
metadata:
  name: videoprocessor
  namespace: production
spec:
  selector:
    app: videoprocessor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: videoprocessor
