apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: production
spec:
  selector:
    app: zookeeper        
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
    name: zookeeper